org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,48)
loader_version_range=[47,)

mod_id=etheriaperfix
mod_name=Etheria Performance Fix
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.konek101.etheriaperfix
mod_authors=konek101
mod_description=Performance optimization patch for the Etheria mod using Mixins
